In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from the_well.data import WellDataset
from torch.utils.data import DataLoader

In [3]:
dataset_path = "datasets/permalloy_varied_field"
IN_CONTEXT_N = 4

train_dataset = WellDataset(
    path=dataset_path,
    well_split_name="train",
    n_steps_input=IN_CONTEXT_N,
    n_steps_output=1,
    use_normalization=False,
)

In [4]:
from pathlib import Path

path = Path("datasets/permalloy_varied_field")
path.name

'permalloy_varied_field'

In [2]:
for k, v in train_dataset[2].items():
    print(k, v.shape)

NameError: name 'train_dataset' is not defined

In [5]:
train_dataset[0]["constant_scalars"][3:]

tensor([ 10899.0645, -18319.7910,      0.0000])

In [13]:
loader = DataLoader(dataset=train_dataset, batch_size=4, shuffle=True)

In [14]:
from utils import prepare_batch

for batch in loader:
    x, y, h = prepare_batch(batch=batch, device="cpu")
    print(h)

tensor([[0.5382, 0.3433],
        [0.3243, 0.0271],
        [0.8050, 0.8079],
        [0.3663, 0.1993]])
tensor([[0.6842, 0.4683],
        [0.6370, 0.2698],
        [0.6842, 0.4683],
        [0.8050, 0.8079]])
tensor([[0.5731, 0.5285],
        [0.1286, 0.4993],
        [0.0111, 0.7189],
        [0.2616, 0.2985]])
tensor([[0.3629, 0.5932],
        [0.0040, 0.8722],
        [0.0856, 0.2368],
        [0.2358, 0.4291]])
tensor([[0.6158, 0.5742],
        [0.3243, 0.0271],
        [0.8323, 0.8706],
        [0.6158, 0.5742]])
tensor([[0.0040, 0.8722],
        [0.8518, 0.8849],
        [0.2225, 0.5186],
        [0.2358, 0.4291]])
tensor([[0.8050, 0.8079],
        [0.2225, 0.5186],
        [0.4858, 0.2497],
        [0.9560, 0.2077]])
tensor([[0.9560, 0.2077],
        [0.1806, 0.3982],
        [0.9431, 0.5113],
        [0.1806, 0.3982]])
tensor([[0.0040, 0.8722],
        [0.8050, 0.8079],
        [0.6842, 0.4683],
        [0.5601, 0.9923]])
tensor([[0.7261, 0.0169],
        [0.3663, 0.1993],
   

KeyboardInterrupt: 

In [8]:
from utils import H_RANGE

H_RANGE

(-39788.735772973836, 39788.735772973836)